#######################################################################################
#                                                                                     #
#  |  ____\ \ / /__   __|  __ \     /\   |  __ \     /\   | \ | | |/ / |  | |  __ \   #
#  | |__   \ V /   | |  | |__) |   /  \  | |__) |   /  \  |  \| | ' /| |  | | |__) |  #
#  |  __|   > <    | |  |  _  /   / /\ \ |  _  /   / /\ \ | . ` |  < | |  | |  ___/   #
#  | |____ / . \   | |  | | \ \  / ____ \| | \ \  / ____ \| |\  | . \| |__| | |       #
#  |______/_/ \_\  |_|  |_|  \_\/_/    \_\_|  \_\/_/    \_\_| \_|_|\_\\____/|_|       #
#                                                                                     #
#######################################################################################

# Placeholders:
#
# %erankup_rank% show player rank
# %erankup_next_rank% show player next rank
# %erankup_next_rank_cost% show player next rank

menu:
  active: true
  name: "&6Menu Rankup"
  rows: 5

# Announce when player RankUp
announce_when_rankup:
  active: true
  message:
    - ""
    - "&6@player &7foi para o Rank &6@rank"
    - ""

# Effects when player RankUP
effects:
  thunder: true
  bat: true

